apiVersion: gateway.bk.tencent.com/v1beta1
kind: BkGatewayResource
metadata:
  name: example-resource
spec:
  http:
    desc: "获取用户列表"
    # 前端请求方法
    methods: ["GET"]
    # 超时配置
    timeout:
      connect: 1s
      read: 1s
      send: 1s
    uri: /testmars
    matchSubPath: false
    # 不使用现有的服务，直接使用自定义的后端
    upstream:
      nodes:
      - host: 127.0.0.1
        port: 8080
        weight: 10
      type: roundrobin
    # 这个要转成 proxy-rewrite 插件来处理（https://apisix.apache.org/zh/docs/apisix/plugins/proxy-rewrite）
    rewrite:
      enabled: true
      # 后端请求头重写（删除使用空字符串表示）
      headers: {}
      # 如何处理环境定义的头，inherit 表示继承环境定义，override 表示覆盖环境定义，append 表示追加环境定义
      stageHeaders: "inherit"
    plugins:
      - name: "limit-req"
        config:
          rate: 1
          burst: 3
          rejected_code: 429
          key: remote_addr
