apiVersion: gateway.bk.tencent.com/v1beta1
kind: BkGatewayStage
metadata:
  name: example-stage
spec:
  # 域名
  domain: prod.example.com
  # 统一前缀
  pathPrefix: /
  # 描述
  desc: "正式环境"
  # 环境变量
  vars:
    runMode: prod
  # 复写后端请求，和资源的配置不同的是，这里只作为默认值
  rewrite:
    enabled: true
    # 后端请求头重写
    headers:
      key1: value1
      key2: value2
  # 插件配置，绑定在环境的所有资源
  plugins:
    - name: "limit-req"
      config:
        rate: 1
        burst: 2
        rejected_code: 429
        key: consumer_name