# permissions for end users to view bkgatewayconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bkgatewayconfig-viewer-role
rules:
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewayconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewayconfigs/status
  verbs:
  - get
