# permissions for end users to edit bkgatewayservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bkgatewayservice-editor-role
rules:
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewayservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewayservices/status
  verbs:
  - get
