# permissions for end users to edit bkgatewayresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bkgatewayresource-editor-role
rules:
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewayresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewayresources/status
  verbs:
  - get
