# permissions for end users to edit bkgatewayconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bkgatewayconfig-editor-role
rules:
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewayconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewayconfigs/status
  verbs:
  - get
