# permissions for end users to view bkgatewayinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bkgatewayinstance-viewer-role
rules:
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewayinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewayinstances/status
  verbs:
  - get
