# permissions for end users to view bkgatewayservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bkgatewayservice-viewer-role
rules:
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewayservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewayservices/status
  verbs:
  - get
