# permissions for end users to edit bkgatewaystages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bkgatewaystage-editor-role
rules:
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewaystages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.bk.tencent.com
  resources:
  - bkgatewaystages/status
  verbs:
  - get
