apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-operator
  template:
    metadata:
      labels:
        app: test-operator
    spec:
      serviceAccountName: testadmin
      containers:
        - name: test-operator
          image: "test-operator:latest"
          imagePullPolicy: IfNotPresent